from brownie import Wei

INT_DEFAULT_VALUE: int = 0
BOOL_DEFAULT_VALUE: bool = False
STRING_DEFAULT: str = "https://QPOKER.io/"
DEPLOYER_ACCOUNT_INDEX: int = 0
INVESTOR_ACCOUNT_INDEX: int = 1
NONE_DEPLOYER_ACCOUNT_INDEX: int = 2
AGENT_ACCOUNT_INDEX: int = 3
ONE_WEI: int = Wei("1 ether")
EMPTY_BALANCE_AMOUNT: int = INT_DEFAULT_VALUE
DIVISOR_ZERO_VALUE: int = INT_DEFAULT_VALUE
LINEAR_RELEASED_DIVISOR_SUPPORTS: list = [10, 100, 1_000, 10_000, 100_000]
MAX_SUPPLY: int = 4_600_000_000 * ONE_WEI
MINIMUM_AMOUNT_TO_SELL: int = 100_000 * ONE_WEI
DEFAULT_MINT_AMOUNT: int = 4_000_000_000 * ONE_WEI
INVALID_LINEAR_RELEASE_PERIOD_IN_DAYS: int = 0
MONTH_IN_DAYS: int = 30
YEAR_IN_DAYS: int = 12 * MONTH_IN_DAYS
ONE_DAY_IN_SECONDS: int = 86400
NOT_OWNER_ERROR_MESSAGE: str = "Ownable: caller is not the owner"
NOT_DEVELOPMENT_ERROR_MESSAGE: str = "development only"
MINT_MORE_THAN_MAX_SUPPLY_ERROR_MESSAGE: str = "cannot mint more than max supply"
INVALID_TRANSFER_MORE_THAN_AVAILABLE_TOKEN_ERROR_MESSAGE: str = (
    "you can not transfer more than available tokens"
)

INVESTOR_ACCOUNT_INDEX = 1


INVALID_LINEAR_RELEASE_DIVISOR_MESSAGE = "TF"
INVALID_AMOUNT_OF_TRANSFER_WITH_LOCKING_MECHANISM_MESSAGE = "TF 2"
LOCKING_MECHANISM_IS_NOT_ACTIVATED = "LM is not activated."
WALLET_ALREADY_HAS_ACTIVATED_LOCKING_MECHANISM = "TF 3"
MEANINGLESS_LOCKING_MECHANISM_ERROR_MESSAGE = "meaningless locking"
INVALID_LINEAR_RELEASE_PERIOD_IN_DAYS_MESSAGE = "LRPDID division on 0"
QMATIC_CONTRACT_NAME_BEFORE_MIGRATING = "QMatic"
QMATIC_CONTRACT_NAME_AFTER_MIGRATING = "Deprecated $QMATIC"
ERC20_INVALID_TRANSFER_MORE_THAN_BALANCE = "ERC20: transfer amount exceeds balance"
